gg:
  jte:
    development-mode: true

spring:
  application:
    name: stableips

  threads:
    virtual:
      enabled: true
  datasource:
    url: ${STABLEIPS_DB_URL}
    username: ${STABLEIPS_DB_USER}
    password: ${STABLEIPS_DB_PWD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        fetch_size: 50
        jdbc:
          batch_size: 200
        order_inserts: true
        order_updates: true
    show-sql: false
    open-in-view: false


# Web3J Configuration
web3j:
  infura:
    url: https://sepolia.infura.io/v3/${INFURA_PROJECT_ID}

# Ethereum Funding Wallet (replace with your funded Sepolia wallet)
wallet:
  funding:
    private-key: ${FUNDED_SEPOLIA_WALLET_PRIVATE_KEY:}
    initial-amount: 0.01

# XRP Ledger Configuration
xrp:
  network:
    url: https://s.altnet.rippletest.net:51234
    type: testnet
  funding:
    address: ""
    secret: ""
    initial-amount: 10

# Blockchain Configuration
blockchain:
  chain-id: 11155111  # Sepolia testnet

# ERC20 Token Contracts
contract:
  # Standard USDC/DAI contracts on Sepolia testnet
  # Note: Sepolia USDC may use 18 decimals instead of the standard 6 decimals
  usdc:
    address: ${USDC_CONTRACT_ADDRESS:0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238}
  dai:
    address: ${DAI_CONTRACT_ADDRESS:0x3e622317f8C93f7328350cF0B56d9eD4C620C5d6}
  # Custom test token contracts (deploy using scripts/deploy-test-tokens.sh)
  test-usdc:
    address: ${TEST_USDC_ADDRESS:}
  test-dai:
    address: ${TEST_DAI_ADDRESS:}

# Initial token amounts for new users (in token units, not smallest denomination)
token:
  funding:
    initial-usdc: 1000
    initial-dai: 1000

# Solana Configuration (Devnet)
solana:
  network:
    url: https://api.devnet.solana.com
  faucet:
    url: https://api.devnet.solana.com
  funding:
    initial-amount: 2

# Logging Configuration
logging:
  level:
    co.grtk.stableips: INFO
  requests:
    enabled: false  # Set to true to enable detailed request logging for debugging

