#!/bin/bash

# Deploy Test Tokens (USDC and DAI) to Sepolia Testnet
# This script uses Remix IDE for deployment (simplest approach)

echo "========================================"
echo "Test Token Deployment Guide"
echo "========================================"
echo ""
echo "This script will guide you through deploying TestUSDC and TestDAI to Sepolia testnet."
echo ""
echo "OPTION 1: Deploy using Remix IDE (Recommended - No local setup needed)"
echo "========================================"
echo ""
echo "1. Open Remix IDE: https://remix.ethereum.org"
echo ""
echo "2. Create a new file: contracts/TestToken.sol"
echo "   - Copy the contents from: $(pwd)/../contracts/TestToken.sol"
echo ""
echo "3. Compile the contract:"
echo "   - Click 'Solidity Compiler' tab"
echo "   - Select compiler version: 0.8.20 or higher"
echo "   - Click 'Compile TestToken.sol'"
echo ""
echo "4. Deploy TestUSDC:"
echo "   - Click 'Deploy & Run Transactions' tab"
echo "   - Environment: 'Injected Provider - MetaMask'"
echo "   - Make sure MetaMask is connected to Sepolia testnet"
echo "   - Constructor parameters:"
echo "     - _name: \"Test USDC\""
echo "     - _symbol: \"USDC\""
echo "     - _decimals: 6"
echo "   - Click 'Deploy'"
echo "   - Confirm transaction in MetaMask"
echo "   - Copy the deployed contract address"
echo ""
echo "5. Deploy TestDAI:"
echo "   - Same steps as TestUSDC, but with:"
echo "     - _name: \"Test DAI\""
echo "     - _symbol: \"DAI\""
echo "     - _decimals: 18"
echo "   - Copy the deployed contract address"
echo ""
echo "6. Update application.properties:"
echo "   Add these lines:"
echo "   contract.test-usdc.address=<TestUSDC_address>"
echo "   contract.test-dai.address=<TestDAI_address>"
echo "   token.funding.initial-usdc=1000"
echo "   token.funding.initial-dai=1000"
echo ""
echo "========================================"
echo ""
echo "OPTION 2: Deploy using Hardhat (Advanced)"
echo "========================================"
echo ""
echo "Prerequisites:"
echo "  - Node.js installed"
echo "  - Hardhat installed: npm install --save-dev hardhat"
echo ""
echo "Coming soon..."
echo ""
echo "========================================"
echo ""
echo "After deployment, you can verify your contracts on Etherscan:"
echo "https://sepolia.etherscan.io/"
echo ""
echo "Then mint test tokens to any address using the 'mint' function in Remix."
echo ""
